---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml
  roles:
    - base
    - db
    - web
