---
- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  vars:
    - update_apt_cache: yes
  tasks:
    - name: Ensure bash, OpenSSl, and libssl are the latest versions
      apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
      with_items:
        - bash
        - openssl
        - libssl-dev
        - libssl-doc
    - name: Install base packages
      apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
      with_items:
        - build-essential
        - ntp
        - htop
        - git
        - python-dev
        - python-pip
        - supervisor
    - name: Install virtualenv
      pip: name=virtualenv
