---

- name: Provision a {{ application_name }} server
  hosts: soundscapes
  remote_user: root
  sudo: yes
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/prod.yml
  roles:
    - base
    - db
    - web
