---
project_name: soundscapes-app
application_name: soundscapes

git_repo: https://github.com/evoapps/soundscapes.git

db_user: "{{ application_name }}"
db_name: "{{ application_name }}"

# Application settings.
virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements/base.txt"

# Gunicorn settings
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps
gunicorn_num_workers: 3
gunicorn_max_requests: 0


# Nginx settings
nginx_server_name: "{{ inventory_hostname }}"
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ virtualenv_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"

ssl_dest_dir: /etc/ssl

# Django Environment variables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
