---

db_password: "soundscapes"

django_settings_file: "settings.dev"
django_secret_key: "soundscapesevoapps"

ssl_crt: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIJAIxj7T5Os4wHMA0GCSqGSIb3DQEBBQUAMCIxIDAeBgNV
  BAMTF3NvdW5kc2NhcGVzLmV2b2FwcHMueHl6MB4XDTE1MDYyNjAxNDQxNloXDTI1
  MDYyMzAxNDQxNlowIjEgMB4GA1UEAxMXc291bmRzY2FwZXMuZXZvYXBwcy54eXow
  ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDOmQA4iZf0HvnuJOEx8M7O
  ah9oCSlrqBJVQCijcLM29or98tiF8AitdLaX8kyaNAyBZvnJEBnCWVF0KDNuZoEM
  /EqsLV45L3mXeTF7Al2zTr4hmpiQ1TUQcnMTjxtu3CFB5GBcmUY+4gNFjYaYIQA7
  3psvj36uqi+q8biflKceqJWxGIuRgQ/IyLSfBsLtzwn7pZduWi+Tr41AT5aFwXyG
  NrNkfNzSR4l8kP6hTz8wcuVv2BbZhTZLxNfWkpd8ihFOOzx03bNAhNHD3qWfXL71
  lP3n646evNu4qjVzW+YrUXz/TyeEUXlZDWV0OBRSL8R6GCSWFlhbcRnhIOCuswZJ
  AgMBAAGjgYQwgYEwHQYDVR0OBBYEFHlY0x1DLrNgUypRfWSdUui8Ea2+MFIGA1Ud
  IwRLMEmAFHlY0x1DLrNgUypRfWSdUui8Ea2+oSakJDAiMSAwHgYDVQQDExdzb3Vu
  ZHNjYXBlcy5ldm9hcHBzLnh5eoIJAIxj7T5Os4wHMAwGA1UdEwQFMAMBAf8wDQYJ
  KoZIhvcNAQEFBQADggEBALEcimPu2VIkULTOq+ZgLDkxufcGukSJ+R4BO9LRd9bC
  FqmP+TRoFEweQbgGXMZBSPaHC23p8w0dkm6GJ+1BPHG99gBDXz7caCnK/KW0P4pv
  0QuCaoxumcQ+fRSJ50Lu11VZ450MnzqCKhAgN9WQPd+kooMmSRNJfT1DmXTA7Ndg
  tqOHG90WK746XgvDHBYTFS/WjuHhYnOnbiI5qqzwHyRuArsiY5L9l57ET8XW71gO
  JA9FG9WVBffO3kpI8doCjc3M/W1SnIm4Tl2HnWeWWI+93UjrYF1oYsEVP/eH0cj5
  xkU5LlukoZG0hwgUTVu50fJE87KoAcPYQ0OGOfN5NhI=
  -----END CERTIFICATE-----

ssl_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAzpkAOImX9B757iThMfDOzmofaAkpa6gSVUAoo3CzNvaK/fLY
  hfAIrXS2l/JMmjQMgWb5yRAZwllRdCgzbmaBDPxKrC1eOS95l3kxewJds06+IZqY
  kNU1EHJzE48bbtwhQeRgXJlGPuIDRY2GmCEAO96bL49+rqovqvG4n5SnHqiVsRiL
  kYEPyMi0nwbC7c8J+6WXblovk6+NQE+WhcF8hjazZHzc0keJfJD+oU8/MHLlb9gW
  2YU2S8TX1pKXfIoRTjs8dN2zQITRw96ln1y+9ZT95+uOnrzbuKo1c1vmK1F8/08n
  hFF5WQ1ldDgUUi/EehgklhZYW3EZ4SDgrrMGSQIDAQABAoIBAQDFREB6u57VIXLB
  2oMQfX/qhlhArWbYfd4repyTGvx0gcrLmsL2ePDANw5WXayZHRPHx3zAaFhAQ6rL
  /8rEIqocrRXb+2HZtqQiZz1A2EyB9rEDQytkN8B4WN/akC3Al/5FfXwpTs1NI9+9
  3NnkjrY7dF23dwueWbA0SKRh873zPYskxMFSBd24Xr2cWpxzmryTzdpZF1sRK9cy
  Dk9AxDGPe3FCuiufJO7+3a2Ksb1mho2Qkte9n3S/jV25iEo1kuIa8nJZfdK5QPBR
  c4Kdj+xBorWGxQEepjVQRhEE2B01sGH73pnZqTjcLaoDiOcVqQlnr17UEUd7nAqW
  2EbFiMRFAoGBAPnsnhA5Ooch9glA3ilRFo2DPoUcXTyZ6SagM9F6xnonNBU/K9pd
  zSiCuJ4i/vG0x18gx+Qamwk0m7thkUG1+8NxJTf0eogolpAO43MFwo5DgyrPpwCV
  +O/PHu1eeAsco1gwYgjn4TeQ6N7MbU3MklytanTz2fH7zwbi0etgwznTAoGBANOe
  vmySwlXhwm619CrBJVJFFXfzxCyUDbzPYrjX5RWf4GCiJnuN5q2gADq5YcQ/JPsU
  p6xEDNZamX8zcpDSLH+xNECuBoHYl3wtbZBzTwgm4g7RF1JPzbHqt3Rd2g7AY52z
  AMgo6/lAZPED90IO9c17QcsHcy8MQdd7j9i0j3HzAoGBAIfnqdR8ql0NlLNXePfS
  xobRlc/gqrrnnyeH+mWxc/i9FM9w+LHYTFX5L9eehDB/8+LA+rIJ3cDVwNHWrpyj
  D3MqNekFoxQjrixMTFciDLg78jn3jYL+Cs6tPM4rju/L9O9h8A2Tup7yyA9P7yhd
  VEHdc4SBjkTOf7fo4+oxRjhNAoGAGez/zVNphZYD+QZHpJlHFj4qdCikJwX4bOJH
  aPfiM/UDSzNyXX6z/R92B7vAc4d841nTdPJdVEGDPqcx6PYmx3oROb9YQr4jSO5T
  1veZfhktZr1NCyOFwr9LvHDnDxmY2rAcb2k8B6xQ8YoX17r3eDYaiGIgRWpOArU7
  mUP9susCgYAYy5aNTkjJghEghH7MqFlzC+Wh6cK7uW5C3K62GmS3EJnrP8Nl5CaJ
  EC+obI0idAFIEBAmMwwmRtLC464BpLQyEvenQfNPdtvTARIiqIRgs5eeF20wG/AU
  Ss1xCtdkmQfUyJ/2qMX3B2Ovy4siShaEWVHp01e9R3mlFwsGoNSb+g==
  -----END RSA PRIVATE KEY-----
