---

- include: install_additional_packages.yml

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml

- include: setup_git_repo.yml
  when: install_github is defined and install_github == False

- include: setup_django_app.yml

- include: setup_supervisor.yml

- include: set_file_permissions.yml

- include: setup_nginx.yml
