---

- name: Install required packages
  pip: requirements={{ requirements_file }}  virtualenv={{ virtualenv_path }} virtualenv_site_packages=yes

- name: Install additional required packages
  easy_install: name=feedparser virtualenv={{ virtualenv_path }}

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
