---

- name: Setup the Git repo
  git: repo={{ git_repo }}
       dest={{ project_path }}
       accept_hostkey=yes

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
