---

- name: Install required packages
  pip: requirements={{ requirements_file }}  virtualenv={{ virtualenv_path }} virtualenv_site_packages=yes

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment

- name: Create media and download directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ virtualenv_path }}/media/"
    - "{{ virtualenv_path }}/downloads/"
    - "{{ virtualenv_path }}/analyses/"
